### PR TITLE
add some tests + use "docker-compose" for travis-ci

### PR DESCRIPTION
**Pull request by voku**
This change is [Reviewable](https://reviewable.io/reviews/mullnerz/test-ci-php/1)

### CODE REVIEW

**Comment by mullnerz** [comment]
@voku Don't know what's your goal :) Mine was just to check how quickly/slowly a Hello World runs on different CI platforms/configurations.

**Comment by voku** [comment]
my goal was to test docker-compose in CI platforms, so that I can run the same tests & command locally and on the CI system, otherwise there is some black-magic-yml-config and nobody can run this on his own local machine. :)

**Comment by mullnerz** [comment]
Not a bad idea :) but than usually that will end up running docker-in-docker, since most CI already executing things inside docker container. What was your experience while checking it?

**Comment by voku** [comment]
I only tested it via travis-ci but that worked quite good. 

What was the result of your "performance" test, what CI server executes the stuff quicker?

**Comment by mullnerz** [comment]
I started this experiment when I realized that running a single hello world in the CI takes quite some time in Gitlab, around 15-20s. Does not matter if you run the commands locally with the gitlab-runner, but if you use the docker executor, it is just this slow. On the shared Gitlab.com it was even slower 30sec to sometimes even slower.

If I shred docker from CI stack, just using the shell executor the same jobs finishes <1s which is what normally people expect. And this was the main outcome for me.

The result with the other CI systems was similar, using their shared service with docker, it usually need time in the range 10-30sec to run the simple hello world job.

But I have the feeling that feature wise Gitlab and Travis are ahead of the others...

**Pull request closed without merging**
